apiVersion: batch/v1
kind: Job
metadata:
  name: scraper-warszawa
  labels:
    city: warszawa
spec:
  template:
    metadata:
      labels:
        city: warszawa
    spec:
      containers:
      - name: scraper
        env:
        - name: CITY
          value: "warszawa"
        - name: PAGES
          valueFrom:
            configMapKeyRef:
              key: warszawa_pages

